config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :lists do
    resources :tasks, only: [:create, :destroy]
  end

  root 'welcome#index'

  

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :tasks, dependent: :destroy

  validates :title, length: { maximum: 40 }, presence: true
  validates_presence_of :user

  scope :title, -> { order('created_at desc') }
end

app/models/sub_task.rb
class SubTask < ActiveRecord::Base
  belongs_to :task

  validates :description, length: { maximum: 20 }, presence: true
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  belongs_to :list
  has_many :sub_tasks, dependent: :destroy

  scope :almost_due, -> { where("time_goal < ?", Time.now + 10.days).order('time_goal asc') }
  default_scope { order('time_goal asc') }
  
  validates :description, length: { maximum: 140 }, presence: true
  validates :time_goal, presence: true
  validates :list, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :lists, dependent: :destroy 
  has_many :tasks, dependent: :destroy       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  def index
    @lists = List.where(user: current_user)
    @tasks = Task.all.almost_due 
  end

  def show
    @list = List.find(params[:id])
    @task = Task.new(list_id: @list.id)
    @tasks = @list.tasks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user

    if @list.save
      flash[:notice] = "To Do List saved."
      redirect_to lists_path
    else
      flash[:error] = "There was an error saving your To Do List. Please try again."
      render :new
    end
  end

  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])

    if @list.update(list_params)
      redirect_to @list
    else
      render 'edit'
    end
  end

  def destroy
    @list = List.find(params[:id])

    if @list.destroy
      flash[:notice] = "To Do List removed."
      redirect_to lists_path
    else
      flash[:error] = "There was a problem removing your List.  Please try again."
      render :show
    end
  end

  private
    def list_params
      params.require(:list).permit(:title)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def create
    @list = List.find(params[:list_id])
    @task = @list.tasks.build(task_params)
    @task.user = current_user
    #@task.list = @list

    if @task.save!
      flash[:notice] = "New task was created."
      redirect_to list_path(@list)
    else
      flash[:error] = "There was a problem saving the task."
      redirect_to list_path(@list)
    end
  end

  def destroy
    @list = List.find(params[:list_id])
    @task = @list.tasks.find(params[:id])
    @task.user = current_user

    if @task.destroy
      flash[:notice] = "Task Completed!"
      redirect_to list_path(@list)
    else
      flash[:error] = "There was a problem removing your Task.  Please try again."
    end
  end

  private
    def task_params
      params.require(:task).permit(:description, :time_goal)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def update
    if params[:user][:password].blank?
      params[:user].delete("password")
      params[:user].delete("password_confirmation")
    end

    @user = User.find(current_user.id)
    if @user.update_attributes(params[:user])
      set_flash_message :notice, :updated
      sign_in @user, :bypass => true
      redirect_to after_update_path_for(@user)
    else
      render "devise/registrations/edit"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to lists_path if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def control_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'control-group error'
    else
      content_tag :div, capture(&block), class: 'control-group'
    end
  end

  def task_url_helper(task)
    list = task.list
    [list, task]
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse">
        <span class="sr-only">Toggle Navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <%= link_to(image_tag("TimeTaskIt-logo.svg", :alt => "logo", :title => "Home"), "/") %>
      </span>
    </div>
    <div class="collapse navbar-collapse breather" id="collapse">
      <ul class="nav navbar-nav">
        <li>
          <% if current_user %>
            <%= link_to "To Do Lists", lists_path %>
          <% end %>
        </li>
      </ul>
      <span class="navbar-right">
        <% if current_user %>
          <p class="navbar-text"> Hello, <span class="navbar-link"><%= link_to (current_user.name || current_user.email), edit_user_registration_path %></span>! </p><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-default navbar-btn' %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path, class: 'btn btn-default navbar-btn' %> 
          <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </span> 
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TimeTaskIt</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class= "container main-container">
    
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#collapse">
            <span class="sr-only">Toggle Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="navbar-brand">
            <%= link_to(image_tag("TimeTaskIt-logo.svg", :alt => "logo", :title => "Home"), "/") %>
          </span>
        </div>
        <div class="collapse navbar-collapse breather" id="collapse">
          <ul class="nav navbar-nav">
            <li>
              <% if current_user %>
                <%= link_to "To Do Lists", lists_path %>
              <% end %>
            </li>
          </ul>
          <span class="navbar-right">
            <% if current_user %>
              <p class="navbar-text"> Hello, <span class="navbar-link"><%= link_to (current_user.name || current_user.email), edit_user_registration_path %></span>! </p><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: 'btn btn-default navbar-btn' %>
            <% else %>
              <%= link_to "Sign In", new_user_session_path, class: 'btn btn-default navbar-btn' %> 
              <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-default navbar-btn' %>
            <% end %>
          </span> 
        </div>
      </div>
    </nav>
    
    <div>
      <% if flash[:notice] %>
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:notice] %>
          </div>
        <% elsif flash[:error] %>
          <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:error] %>
          </div>
        <% elsif flash[:alert] %>
          <div class="alert alert-info alert-dismissable">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <%= flash[:alert] %>
          </div>  
        <% end %> 

      <%= yield %>

    </div>
  </div> 
</body>
<footer class="navbar navbar-fixed-bottom hidden-xs"></footer>
</html>

app/views/lists/_list_form.html.erb
<%= form_for @list, html: { class: 'form-inline'} do |f| %>
  
  <%= f.label :title, class: 'sr-only' %>
  <%= f.text_field :title, class: 'form-control' %>

  <%= f.submit "Save", class: 'btn btn-success  btn-sm' %>
<% end %>

app/views/lists/edit.html.erb
<div class="col-md-offset-1 breather">
  <%= render partial: 'list_form' %>
</div>

app/views/lists/index.html.erb
<div class="row">
  <div class="col-md-6 col-xs-12">
    <h1>To Do Lists</h1>
    <div class="table-responsive">
      <table class="table table-hover">
        <% @lists.each do |list| %>
          <tr>
            <td class="col-md-10 list-text"><%= link_to list.title, list %></td>
            <td class="col-md-1"><span class="badge"><%= list.tasks.count %></span></td>
            <td class="col-md-1"><%= link_to "Remove", list_path(list), method: :delete, class: 'btn btn-danger btn-xs' %>     
            </td>
          </tr>
        <% end %>
      </table>
    </div>
    <%= link_to "New List", new_list_path, class: 'btn btn-primary' %>
  </div>
  <div class="col-md-5 col-md-offset-1 col-xs-12">
    <h1>Upcomming Tasks</h1>
    <div class="table-responsive">
      <table class="table table-hover">
        <tr>
          <th class="col-md-8 white-text">Task</th>
          <th class="col-md-3 white-text">List</th>
          <th class="col-md-1 white-text">Time</th>
        </tr>

        <% @tasks.each do |task| %>
          <tr>
            <td class="col-md-8 list-text"><%= task.description %></td>
            <td class="col-md-3"><%= task.list.title %></td>
            <td class="col-md-1"><span class="badge"><%= distance_of_time_in_words(Time.now, task.time_goal) %></span>     
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<div class="col-md-offset-1 breather">
  <%= render partial: 'list_form' %>
</div>

app/views/lists/show.html.erb
<div class="row">
  <div class="col-md-4">
    <div class="row breather">
      <h1 class="centered-text"><%= @list.title %></h1>
      <div class="col-md-6 col-md-offset-3 breather-lg">
        <%= link_to "Edit", edit_list_path(@list), class: 'btn btn-info' %>
        <%= link_to "Back", lists_path, class: 'btn btn-primary' %>
      </div>
    </div>
    <div class="row breather-lg">
      <div class="col-md-6 col-md-offset-3">
        <%= render partial: 'tasks/form', locals: { list: @list, task: @task } %>
      </div>
    </div>
  </div>
  <div class="col-md-8 breather-xl">
    <%= render partial: 'tasks/task', locals: { list: @list } %>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_for [ list, task], html: { role: "form" } do |f| %>
  <div class="form-group">
    <%= f.label :description, "Task Description" %>
    <%= f.text_area :description, rows: 3, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :time_goal, "Date to Complete by" %></br>
    <%= f.date_select :time_goal, class: 'form-control', :order => [:month, :day, :year] %>
  </div>

  <div class="form-group">
    <%= f.submit "Save Task", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="table-responsive">
  <table class="table">
    <tr>
      <th class="col-md-7 white-text">Task</th>
      <th class="col-md-2 centered-text white-text">Time Remaining</th>
      <th class="col-md-1 white-text">Complete</th>
    </tr>

    <% @list.tasks.each do |task| %>
      <tr>
        <td class="col-md-7 list-text"><%= task.description %></td>
        <td class="col-md-2 centered-text"><span class="badge"><%= distance_of_time_in_words(Time.now, task.time_goal) %></span></td>
        <td class="col-md-1"><%= link_to "Done !", task_url_helper(task), method: :delete, class: 'btn btn-primary btn-sm' %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/tasks/create.html.erb
<%= form_for [list, task], html: { class: 'form-inline'} do |f| %>
  
  <%= f.label :description, class: 'sr-only' %>
  <%= f.text_field :description, class: 'form-control' %>

  <%= f.submit "Save", class: 'btn btn-success  btn-sm' %>
<% end %>

app/views/welcome/index.html.erb
<div class="row">
  <div class="jumbotron">
    <div class="col-md-5 col-xs-6">
      <div class="pull-right">
        <%= image_tag("clock.svg", :alt => "Time Task It Logo", :class => "img-responsive") %>
      </div>
    </div>
    <div class="col-md-7 col-xs-6">
      <div class="pull-left">
        <h1>Time Task It</h1>
        <p>In a sea of things to do, </br>prioritize your life!</p>
      </div>
    </div>
  </div>
</div>
<div class="container sign-up-band">
  <div class="row">
    <div class="col-md-5 col-md-offset-1">
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-default btn-lg pull-left breather-side' %>
      <h4 class="white-text breather">Sign up for Free today!</h4>
    </div>  
  </div>
</div>
<div class="row breather-xl"> 
  <div class="col-md-8 col-xs-8">
    <div class="background-box">
      <div class="inside-background-box text-center">
        <h4>Keep Your Lists Organized</h4>
        <hr/>
        <p class="hidden-xs">Most likely, you've got alot going on in your life.  Keep track of all those different aspects of life you're trying to juggle organized with customized lists.  Make as many as you need, to keep the tasks they contain seperate so you can focus on what you need when you have the time to do it.</p>
      </div>
    </div>
  </div>
  <div class="col-md-4 col-xs-4 center">
    <div class="breather">
      <%= image_tag("Octopus.svg", :alt => "Expired Tasks Self Destruct", :class => "img-responsive") %>
    </div>
  </div>
</div>

<div class="row breather-xl"> 
  <div class="col-md-4 col-xs-4 center">
    <%= image_tag("Shark.svg", :alt => "Expired Tasks Self Destruct", :class => "img-responsive") %>
  </div>
  <div class="col-md-8 col-xs-8">
    <div class="background-box">
      <div class="inside-background-box text-center">
        <h4>Keep Up on Upcomming Deadlines</h4>
        <hr/>
        <p class="hidden-xs">Forgot about something?  We keep track of all of your upcoming deadlines and put them in one place on your start screen.  All upcomming tasks are displayed so that if there is something coming up on a list you've forgotten about, it will come out of hiding.  We help you manage all the tasks that ussually fall into obscurity.</p>
      </div>
    </div>
  </div>
  
</div>

<div class="row breather-xl"> 
  <div class="col-md-8 col-xs-8">
    <div class="background-box">
      <div class="inside-background-box text-center">
        <h4>Get Rid of Unwanted Clutter</h4>
        <hr/>
        <p class="hidden-xs">To Do lists are notorius for collecting lots of clutter.  With TimeTaskIt, we take care of that for you!  When a task passes it's deadline, the task automatically self destructs.  No more cluttered to do lists with things you just haven't gotten around to doing.  Because, let's be honest, if you haven't gotten done by then you weren't going to get around to doing it.</p>
      </div>
    </div>
  </div>
  <div class="col-md-4 col-xs-4 center">
    <%= image_tag("deep-sea-mine.svg", :alt => "Expired Tasks Self Destruct", :class => "img-responsive") %>
  </div>
</div>